apiVersion: v1
kind: Secret
metadata:
  name: bank-backend-secret
type: Opaque
data:
  DB_USERNAME: Ym9vdGhl
  DB_PASSWORD: Qm9vdGhlQCMwMQ==


## echo -n "root" | base64
## echo -n "password123ABC" | base64
